apiVersion: apps/v1
kind: Deployment
metadata:
  name: strike2-db
  namespace: strike
  labels:
    app: strike2-db
spec:
  selector:
    matchLabels:
      app: strike2-db
  template:
    metadata:
      labels:
        app: strike2-db
    spec:
      containers:
      - name: strike2-db
        image: strike2-db 
        ports:
        - containerPort: 5432
        envFrom:
            - secretRef:
                name: strike-db-env
