apiVersion: apps/v1
kind: Deployment
metadata:
  name: strike-server1
  namespace: strike
  labels:
    app: strike-server1
spec:
  selector:
    matchLabels:
      app: strike-server1
  template:
    metadata:
      labels:
        app: strike-server1
    spec:
      containers:
      - name: strike-server1
        image: strike_server
        ports:
        - containerPort: 8080
        envFrom:
            - secretRef:
                name: strike-server1-env
        volumeMounts:
            - name: strike-server1-identity
              mountPath: /etc/strike-server-identity
              readOnly: true
            - name: strike-federation
              mountPath: /etc/strike-federation
      volumes:
        - name: strike-server1-identity
          secret:
            secretName: strike-server1-identity
        - name: strike-federation
          secret:
            secretName: strike-federation
