apiVersion: v1
kind: Service
metadata:
  name: strike-server2
  namespace: strike
spec:
  selector:
    app: strike-server2
  ports:
    - name: grpc-client
      port: 8080
      targetPort: 8081
    - name: grpc-federation
      port: 9090    
      targetPort: 9091
