apiVersion: v1
kind: Service
metadata:
  name: strike-server1
  namespace: strike
spec:
  selector:
    app: strike-server1
  ports:
    - name: grpc-client
      port: 8080
      targetPort: 8080
    - name: grpc-federation
      port: 9090
      targetPort: 9090
