peers:
  - id: "endpoint0-UUID"
    name: "endpoint0"
    addr: "strike-server1:9090"
    pubkey: "signing-key"
    # cert? /
  - id: "federated-server-UUID"
    name: "endpoint1"
    addr: "strike-server2:9090"
    pubkey: "signing-key-federated"
